# Generated by Django 5.1.1 on 2025-09-19 15:10

import lamp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamp',
            name='led_start',
            field=models.TimeField(default=lamp.models.default_time),
        ),
        migrations.AlterField(
            model_name='lamp',
            name='light_start',
            field=models.TimeField(default=lamp.models.default_time),
        ),
        migrations.AlterField(
            model_name='lamp',
            name='light_stop',
            field=models.TimeField(default=lamp.models.default_time),
        ),
    ]
