# Generated by Django 5.1.1 on 2025-03-27 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lamp", "0025_alter_lamp_light_start_alter_lamp_light_stop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lamp",
            name="light_start",
            field=models.TimeField(default=datetime.datetime(2025, 3, 27, 17, 10)),
        ),
        migrations.AlterField(
            model_name="lamp",
            name="light_stop",
            field=models.TimeField(default=datetime.datetime(2025, 3, 27, 17, 10)),
        ),
    ]
