# Generated by Django 5.1.1 on 2025-08-29 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0041_alter_lamp_light_start_alter_lamp_light_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='light_start',
            field=models.TimeField(default=datetime.datetime(2025, 8, 29, 18, 2)),
        ),
        migrations.AlterField(
            model_name='lamp',
            name='light_stop',
            field=models.TimeField(default=datetime.datetime(2025, 8, 29, 18, 2)),
        ),
    ]
