# Generated by Django 5.1.1 on 2025-09-04 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0056_alter_lamp_light_start_alter_lamp_light_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='light_start',
            field=models.TimeField(default=datetime.datetime(2025, 9, 4, 14, 45)),
        ),
        migrations.AlterField(
            model_name='lamp',
            name='light_stop',
            field=models.TimeField(default=datetime.datetime(2025, 9, 4, 14, 45)),
        ),
    ]
