# Generated by Django 5.1.1 on 2025-12-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField()),
                ('to_device', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='firmware_device/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
