# Generated by Django 5.1.1 on 2025-09-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('visibility', models.CharField(choices=[('PR', 'private'), ('PU', 'public')], default='PU', max_length=2)),
            ],
        ),
    ]
