# Generated by Django 5.1.1 on 2025-03-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_favourite',
        ),
    ]
