# Generated by Django 5.1.1 on 2025-03-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.device')),
                ('time', models.DateTimeField()),
                ('value', models.FloatField()),
                ('humi', models.FloatField(default='')),
            ],
            bases=('device.device',),
        ),
    ]
