# Generated by Django 5.1.1 on 2025-10-11 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_remove_device_ip_remove_device_port'),
        ('temperature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempHum',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.device')),
                ('battery_level', models.IntegerField(default=0)),
            ],
            bases=('device.device',),
        ),
        migrations.DeleteModel(
            name='TemperatureSensor',
        ),
    ]
