# Generated by Django 5.1.1 on 2025-10-15 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0002_temphum_delete_temperaturesensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='temphum',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='temphum',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='temphum',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
