# Generated by Django 5.1.1 on 2025-10-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0003_temphum_humidity_temphum_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temphum',
            name='humidity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='temphum',
            name='temperature',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
