# Generated by Django 5.1.1 on 2025-10-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0004_alter_temphum_humidity_alter_temphum_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temphum',
            name='battery_level',
        ),
        migrations.AddField(
            model_name='temphum',
            name='humidity_hysteresis',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='temphum',
            name='temperature_hysteresis',
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name='temphum',
            name='trigger_hum_down',
            field=models.FloatField(default=30),
        ),
        migrations.AddField(
            model_name='temphum',
            name='trigger_hum_up',
            field=models.FloatField(default=70),
        ),
        migrations.AddField(
            model_name='temphum',
            name='trigger_temp_down',
            field=models.FloatField(default=15),
        ),
        migrations.AddField(
            model_name='temphum',
            name='trigger_temp_up',
            field=models.FloatField(default=25),
        ),
    ]
