# Generated by Django 5.1.1 on 2025-03-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
        ('lamp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rfid',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.device')),
                ('controlled_lamp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lamp.lamp')),
            ],
            bases=('device.device',),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('uid', models.IntegerField(default=0)),
                ('rfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfid.rfid')),
            ],
        ),
    ]
