# Generated by Django 5.1.1 on 2025-11-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfid',
            name='button_type',
            field=models.CharField(choices=[('MONO', 'Monostable'), ('BI', 'Bistable')], default='MONO', max_length=5),
        ),
    ]
