# Generated by Django 5.1.1 on 2025-03-02 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='last_use',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
