# Generated by Django 5.1.1 on 2025-03-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0002_card_last_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='last_use',
            new_name='last_used',
        ),
    ]
