# Generated by Django 5.1.1 on 2025-03-13 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0003_rename_last_use_card_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rfid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='rfid.rfid'),
        ),
        migrations.AlterField(
            model_name='card',
            name='uid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
