# Generated by Django 5.1.1 on 2025-03-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0004_alter_card_rfid_alter_card_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
