# Generated by Django 5.1.1 on 2025-03-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0005_alter_card_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='uid',
            field=models.IntegerField(unique=True),
        ),
    ]
