# Generated by Django 5.1.1 on 2025-03-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfid", "0006_alter_card_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="uid",
            field=models.BigIntegerField(unique=True),
        ),
    ]
