# Generated by Django 5.1.1 on 2025-03-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rfid", "0007_alter_card_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rfid",
            name="controlled_lamp",
        ),
    ]
