# Generated by Django 5.1.1 on 2025-09-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='port',
            field=models.PositiveIntegerField(default=554),
        ),
    ]
