# Generated by Django 5.1.1 on 2025-09-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_alter_camera_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
