# Generated by Django 5.1.1 on 2026-01-20 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("device", "0005_device_chip_type_alter_device_fun_alter_device_mac"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stairs",
            fields=[
                (
                    "device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="device.device",
                    ),
                ),
                ("brightness", models.SmallIntegerField(default=100)),
                ("step", models.SmallIntegerField(default=21)),
                ("lighting_time", models.SmallIntegerField(default=10)),
                ("stair_count", models.IntegerField(default=16)),
            ],
            bases=("device.device",),
        ),
    ]
