# Generated by Django 5.1.1 on 2026-01-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stairs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stairs",
            old_name="stair_count",
            new_name="light_count",
        ),
    ]
