# Generated by Django 5.1.1 on 2025-03-02 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('fun', models.CharField(default='', max_length=100)),
                ('last_seen', models.DateTimeField()),
                ('mac', models.CharField(default='', max_length=100)),
                ('is_favourite', models.BooleanField(default=False)),
                ('wifi_strength', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=100)),
                ('answer', models.CharField(default='', max_length=100)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=40)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
