# Generated by Django 5.1.1 on 2025-09-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(default='Nieznane', max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('fun', models.CharField(default='', max_length=100)),
                ('mac', models.CharField(default='', max_length=100)),
                ('wifi_strength', models.IntegerField(default=0)),
                ('pending', models.JSONField(blank=True, default=list)),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=100)),
                ('answer', models.CharField(default='', max_length=100)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, null=True)),
                ('event', models.CharField(max_length=100, null=True)),
                ('extra_settings', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=100)),
                ('mac', models.CharField(max_length=100)),
                ('wifi_strength', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
    ]
