# Generated by Django 5.1.1 on 2025-09-16 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
        ('room', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='user.home'),
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='room.room'),
        ),
        migrations.AddField(
            model_name='event',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='device.device'),
        ),
        migrations.AddField(
            model_name='event',
            name='target_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device'),
        ),
        migrations.AddField(
            model_name='router',
            name='home',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='router', to='user.home'),
        ),
    ]
