# Generated by Django 5.1.1 on 2025-09-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='device',
            name='port',
        ),
    ]
