# Generated by Django 5.1.1 on 2025-03-13 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_remove_device_is_favourite'),
        ('user', '0005_alter_home_add_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(default='', max_length=100)),
                ('mac', models.CharField(max_length=100, unique=True)),
                ('wifi_strength', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='router', to='user.home')),
            ],
        ),
    ]
