# Generated by Django 5.1.1 on 2025-12-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_remove_device_ip_remove_device_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='firmware_version',
            field=models.FloatField(default=1.0),
        ),
    ]
