# Generated by Django 5.1.1 on 2025-03-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_router'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='mac',
            field=models.CharField(default='', max_length=100),
        ),
    ]
