# Generated by Django 5.1.1 on 2026-01-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0004_device_firmware_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="chip_type",
            field=models.CharField(
                choices=[
                    ("ESP32", "esp32"),
                    ("ESP8266", "esp8266"),
                    ("ESP8266_01", "esp8266_01"),
                ],
                default="ESP32",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="fun",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="device",
            name="mac",
            field=models.CharField(max_length=100),
        ),
    ]
