# Generated by Django 5.1.1 on 2025-03-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_alter_router_mac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='name',
        ),
        migrations.AlterField(
            model_name='router',
            name='mac',
            field=models.CharField(max_length=100),
        ),
    ]
