# Generated by Django 5.1.1 on 2025-03-15 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_alter_device_room'),
        ('user', '0015_alter_home_add_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='user.home'),
        ),
    ]
