# Generated by Django 5.1.1 on 2025-03-15 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_device_home'),
        ('room', '0003_remove_room_is_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='room.room'),
        ),
    ]
