# Generated by Django 5.1.1 on 2025-03-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0009_alter_device_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
