# Generated by Django 5.1.1 on 2025-03-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0010_device_is_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="router",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
