# Generated by Django 5.1.1 on 2025-03-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0011_router_is_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="last_seen",
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(default="Nieznane", max_length=100),
        ),
    ]
