# Generated by Django 5.1.1 on 2025-03-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0012_alter_device_last_seen_alter_device_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="is_online",
        ),
    ]
