# Generated by Django 5.1.1 on 2025-03-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0013_remove_device_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='pending',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
