# Generated by Django 5.1.1 on 2025-03-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0014_device_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='pending',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
