# Generated by Django 5.1.1 on 2025-03-29 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0015_alter_device_pending"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="message",
        ),
        migrations.AddField(
            model_name="event",
            name="action",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="extra_settings",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="event",
            name="target_device",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="device.device",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="device.device",
            ),
        ),
    ]
