# Generated by Django 5.1.1 on 2025-03-29 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0016_remove_event_date_remove_event_message_event_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="device.device",
            ),
        ),
    ]
