# Generated by Django 5.1.1 on 2025-04-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0018_device_is_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
