# Generated by Django 5.1.1 on 2025-05-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0020_alter_device_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="last_seen",
            field=models.DateTimeField(auto_created=True),
        ),
    ]
