# Generated by Django 5.1.1 on 2025-09-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0021_alter_device_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
