# Generated by Django 5.1.1 on 2025-03-02 13:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aquarium',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.device')),
                ('color_r', models.SmallIntegerField(default=255)),
                ('color_g', models.SmallIntegerField(default=255)),
                ('color_b', models.SmallIntegerField(default=255)),
                ('led_start', models.TimeField(default=django.utils.timezone.now)),
                ('led_stop', models.TimeField(default=django.utils.timezone.now)),
                ('fluo_start', models.TimeField(default=django.utils.timezone.now)),
                ('fluo_stop', models.TimeField(default=django.utils.timezone.now)),
                ('mode', models.BooleanField(default=False)),
                ('led_mode', models.BooleanField(default=False)),
                ('fluo_mode', models.BooleanField(default=False)),
            ],
            bases=('device.device',),
        ),
    ]
