# Generated by Django 5.1.1 on 2025-05-01 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquarium", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aquarium",
            name="fluo_start",
            field=models.TimeField(default=datetime.time(10, 56, 6, 679171)),
        ),
        migrations.AlterField(
            model_name="aquarium",
            name="fluo_stop",
            field=models.TimeField(default=datetime.time(10, 56, 6, 679191)),
        ),
        migrations.AlterField(
            model_name="aquarium",
            name="led_start",
            field=models.TimeField(default=datetime.time(10, 56, 6, 678661)),
        ),
        migrations.AlterField(
            model_name="aquarium",
            name="led_stop",
            field=models.TimeField(default=datetime.time(10, 56, 6, 679171)),
        ),
    ]
