# Generated by Django 5.1.1 on 2025-09-06 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0024_alter_aquarium_fluo_start_alter_aquarium_fluo_stop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquarium',
            name='fluo_start',
            field=models.TimeField(default=datetime.datetime(2025, 9, 6, 18, 4)),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='fluo_stop',
            field=models.TimeField(default=datetime.datetime(2025, 9, 6, 18, 4)),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='led_start',
            field=models.TimeField(default=datetime.datetime(2025, 9, 6, 18, 4)),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='led_stop',
            field=models.TimeField(default=datetime.datetime(2025, 9, 6, 18, 4)),
        ),
    ]
