# Generated by Django 5.1.1 on 2025-11-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='button_type',
            field=models.CharField(choices=[('MONO', 'Monostable'), ('BI', 'Bistable')], default='BI', max_length=5),
        ),
    ]
