# Generated by Django 5.1.1 on 2025-11-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='type',
            field=models.CharField(choices=[('MONO', 'Monostable'), ('BI', 'Bistable')], default='MONO', max_length=5),
        ),
    ]
