# Generated by Django 5.1.1 on 2025-11-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0002_button_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='button',
            old_name='type',
            new_name='button_type',
        ),
    ]
