# Generated by Django 5.1.1 on 2025-09-16 17:07

import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('device', '0001_initial'),
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('device', models.ManyToManyField(to='device.device')),
                ('room', models.ManyToManyField(to='room.room')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_uid', models.UUIDField(default=user.models.get_unique_uuid)),
                ('users', models.ManyToManyField(related_name='home', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
