# Generated by Django 5.1.1 on 2025-03-02 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('device', '0002_initial'),
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_uid', models.UUIDField(default=uuid.UUID('53a4dc50-fe78-4967-84ed-c255d396d153'))),
                ('users', models.ManyToManyField(related_name='home', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
