# Generated by Django 5.1.1 on 2025-03-02 15:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('acc0bc8e-b563-42d3-859c-65e7e0b4abb5')),
        ),
    ]
