# Generated by Django 5.1.1 on 2025-03-02 15:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('af82be18-0eda-49bf-a848-675a7f94c01f')),
        ),
    ]
