# Generated by Django 5.1.1 on 2025-03-02 16:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_remove_device_is_favourite'),
        ('room', '0003_remove_room_is_favourite'),
        ('user', '0003_alter_home_add_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='device',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='room',
        ),
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('15fd098a-c57e-4388-ae28-ea6368db91e6')),
        ),
        migrations.AddField(
            model_name='favourite',
            name='device',
            field=models.ManyToManyField(to='device.device'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='room',
            field=models.ManyToManyField(to='room.room'),
        ),
    ]
