# Generated by Django 5.1.1 on 2025-03-13 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_favourite_device_remove_favourite_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('f8dcbdb1-6ca8-4a60-a4de-9030a54df8c3')),
        ),
    ]
