# Generated by Django 5.1.1 on 2025-03-13 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('ec2cfb8c-2ebd-4223-bedf-64bdb4866caa')),
        ),
    ]
