# Generated by Django 5.1.1 on 2025-03-13 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('57a86fb3-3008-4aa5-b83c-630f1fd1e0f3')),
        ),
    ]
