# Generated by Django 5.1.1 on 2025-03-13 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('591d15b2-68a1-498b-a494-827568198376')),
        ),
    ]
