# Generated by Django 5.1.1 on 2025-03-13 18:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('0151a1f3-6b4d-4c67-aec2-56dfdfc893e5')),
        ),
    ]
