# Generated by Django 5.1.1 on 2025-03-13 18:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('d31db0c3-b4bc-48f2-9618-8623675e8979')),
        ),
    ]
