# Generated by Django 5.1.1 on 2025-03-13 18:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('9ca0c449-8738-4c39-94a5-8c1f73cc3270')),
        ),
    ]
