# Generated by Django 5.1.1 on 2025-03-15 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('638e8924-d7ab-4513-9df2-45b918273077')),
        ),
    ]
