# Generated by Django 5.1.1 on 2025-03-15 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('6150d41d-7289-4b63-b8c7-93dcc8576644')),
        ),
    ]
