# Generated by Django 5.1.1 on 2025-03-15 09:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('9c69c930-03f0-4307-b311-0ee859fcfb56')),
        ),
    ]
