# Generated by Django 5.1.1 on 2025-03-15 18:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_alter_home_add_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="add_uid",
            field=models.UUIDField(
                default=uuid.UUID("9939f837-a338-4c0f-af2d-3c7096a12558")
            ),
        ),
    ]
