# Generated by Django 5.1.1 on 2025-03-18 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_alter_home_add_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="add_uid",
            field=models.UUIDField(
                default=uuid.UUID("7b5e4c03-0103-4b37-9fb4-c074ccf9f7d8")
            ),
        ),
    ]
