# Generated by Django 5.1.1 on 2025-03-18 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_alter_home_add_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="add_uid",
            field=models.UUIDField(
                default=uuid.UUID("91c79a7e-53c0-4fd2-91aa-81480db1fc9d")
            ),
        ),
    ]
