# Generated by Django 5.1.1 on 2025-03-21 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('18345ab2-5044-4c7c-8d2c-86ac6c2c73f7')),
        ),
    ]
