# Generated by Django 5.1.1 on 2025-03-22 07:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('6aa87fb0-017e-440a-9127-9dfbaf532490')),
        ),
    ]
