# Generated by Django 5.1.1 on 2025-03-22 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('362b7317-dfc2-4567-a4d1-f8398bc3d0d0')),
        ),
    ]
