# Generated by Django 5.1.1 on 2025-03-22 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('ecd7e4bd-48e9-48ea-96c0-da4ccc5c5d95')),
        ),
    ]
