# Generated by Django 5.1.1 on 2025-03-25 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0024_alter_home_add_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="add_uid",
            field=models.UUIDField(
                default=uuid.UUID("28b28f74-f0b1-4998-9be3-eab90d9544e6")
            ),
        ),
    ]
