# Generated by Django 5.1.1 on 2025-03-25 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0025_alter_home_add_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="add_uid",
            field=models.UUIDField(
                default=uuid.UUID("a3cb5062-221d-4045-b76c-b473ee80771e")
            ),
        ),
    ]
