# Generated by Django 5.1.1 on 2025-03-28 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0027_alter_home_add_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="add_uid",
            field=models.UUIDField(
                default=uuid.UUID("a1ecd255-dbef-4e53-82fe-dee30e9c1c7d")
            ),
        ),
    ]
