# Generated by Django 5.1.1 on 2025-03-29 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0028_alter_home_add_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="add_uid",
            field=models.UUIDField(
                default=uuid.UUID("10765cbc-35b5-49db-a3f2-40ddab588922")
            ),
        ),
    ]
