# Generated by Django 5.1.1 on 2025-03-29 18:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0029_alter_home_add_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="add_uid",
            field=models.UUIDField(
                default=uuid.UUID("98d997b4-dd89-4516-94aa-a1a769df0556")
            ),
        ),
    ]
