# Generated by Django 5.1.1 on 2025-04-06 10:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0030_alter_home_add_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="add_uid",
            field=models.UUIDField(
                default=uuid.UUID("f36617c2-1d8b-4448-9b72-ef6614a3ca53")
            ),
        ),
    ]
