# Generated by Django 5.1.1 on 2025-04-12 08:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0031_alter_home_add_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="add_uid",
            field=models.UUIDField(
                default=uuid.UUID("76725915-c276-4130-9884-7b605f584fbb")
            ),
        ),
    ]
