# Generated by Django 5.1.1 on 2025-04-12 09:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0032_alter_home_add_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="add_uid",
            field=models.UUIDField(
                default=uuid.UUID("d23aa9b5-40ef-4f7d-a880-2b9c7c4d151f")
            ),
        ),
    ]
