# Generated by Django 5.1.1 on 2025-05-01 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0033_alter_home_add_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="add_uid",
            field=models.UUIDField(
                default=uuid.UUID("a82aacd5-b290-47c0-a242-732547f3371d")
            ),
        ),
    ]
