# Generated by Django 5.1.1 on 2025-05-01 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('e9d1b87b-b660-420b-b542-8eafdf59f0a0')),
        ),
    ]
