# Generated by Django 5.1.1 on 2025-05-01 10:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0035_alter_home_add_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="add_uid",
            field=models.UUIDField(
                default=uuid.UUID("883724aa-e658-41cd-909f-903b3970d226")
            ),
        ),
    ]
