# Generated by Django 5.1.1 on 2025-05-01 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0036_alter_home_add_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="add_uid",
            field=models.UUIDField(
                default=uuid.UUID("cb6d0282-3b71-4281-9851-95481142ecd8")
            ),
        ),
    ]
