# Generated by Django 5.1.1 on 2025-05-01 10:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0037_alter_home_add_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="add_uid",
            field=models.UUIDField(
                default=uuid.UUID("fd40f5fe-8a48-4a81-b951-91c005611a33")
            ),
        ),
    ]
