# Generated by Django 5.1.1 on 2025-05-01 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0038_alter_home_add_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="add_uid",
            field=models.UUIDField(
                default=uuid.UUID("d3c14cc9-2113-411d-8592-c97d5a24f891")
            ),
        ),
    ]
