# Generated by Django 5.1.1 on 2025-07-11 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0039_alter_home_add_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="add_uid",
            field=models.UUIDField(
                default=uuid.UUID("d670b7a2-2602-4442-b756-3891c7252737")
            ),
        ),
    ]
