# Generated by Django 5.1.1 on 2025-08-29 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('c2839b3a-c76c-49ac-9cb9-1cddfd5dc128')),
        ),
    ]
