# Generated by Django 5.1.1 on 2025-08-29 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('a5c716bb-8dcb-47ad-abd7-45d8500911bf')),
        ),
    ]
