# Generated by Django 5.1.1 on 2025-08-29 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('412fed1e-03ca-4bb0-a2b1-5ecec3797d45')),
        ),
    ]
