# Generated by Django 5.1.1 on 2025-08-30 12:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('32390227-c846-4a92-af97-5fe51b68f2fa')),
        ),
    ]
