# Generated by Django 5.1.1 on 2025-08-30 13:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('8f677646-dff2-49a7-8a61-90be70099606')),
        ),
    ]
