# Generated by Django 5.1.1 on 2025-09-01 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('eb3cc8c6-e596-4c99-85aa-d9ace4890349')),
        ),
    ]
