# Generated by Django 5.1.1 on 2025-09-01 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('2f02d503-23b2-4d8c-9882-4af435c66f83')),
        ),
    ]
