# Generated by Django 5.1.1 on 2025-09-01 14:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('febb48f0-70f1-4d39-a7b1-656e89d0bcad')),
        ),
    ]
