# Generated by Django 5.1.1 on 2025-09-01 15:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('c07f613f-a707-422b-999b-a9d50c8f07a8')),
        ),
    ]
