# Generated by Django 5.1.1 on 2025-09-01 15:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('3a488173-a9b9-432b-9a2e-5ed58797b915')),
        ),
    ]
