# Generated by Django 5.1.1 on 2025-09-01 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('53ff8791-8e4c-478d-9c78-370cbca4f8cf')),
        ),
    ]
