# Generated by Django 5.1.1 on 2025-09-01 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('a597fb30-0315-480f-bc42-8de2a4af35a5')),
        ),
    ]
