# Generated by Django 5.1.1 on 2025-09-01 17:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('5dfccfe5-df0c-43f9-b3cb-311565977514')),
        ),
    ]
