# Generated by Django 5.1.1 on 2025-09-02 13:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('9b405920-795f-45b4-892c-be1826ba9fac')),
        ),
    ]
