# Generated by Django 5.1.1 on 2025-09-02 18:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('17abc336-7b13-4a92-ba8b-4c83b10565c4')),
        ),
    ]
