# Generated by Django 5.1.1 on 2025-09-03 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('e588587e-88aa-45b6-ad28-5805e3f3a31e')),
        ),
    ]
