# Generated by Django 5.1.1 on 2025-09-04 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('6963cf47-f93a-4e05-87eb-e5820b61e864')),
        ),
    ]
