# Generated by Django 5.1.1 on 2025-09-06 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('541b4270-d1cb-4d1e-aeac-a2386d1be586')),
        ),
    ]
