# Generated by Django 5.1.1 on 2025-09-06 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0059_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('e496a1ab-8fef-49d4-8d0a-22039cfd634f')),
        ),
    ]
