# Generated by Django 5.1.1 on 2025-09-06 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('bdd268a7-8bf6-4c02-944a-e69397da5713')),
        ),
    ]
