# Generated by Django 5.1.1 on 2025-09-06 16:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('145a0050-9498-4cd0-89bf-373cf48bc16d')),
        ),
    ]
