# Generated by Django 5.1.1 on 2025-09-06 16:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('41b9eeaf-818a-4872-9ee4-012fd24c6461')),
        ),
    ]
