# Generated by Django 5.1.1 on 2025-09-07 09:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0063_alter_home_add_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='add_uid',
            field=models.UUIDField(default=uuid.UUID('c5db2364-586e-4b30-9bb4-bbc287e1bcc4')),
        ),
    ]
