name: Deploy on Docker Hub

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/smart-home-backend:latest
          build-args: |
            REQUIREMENTS=requirements/prod.txt
